### PR TITLE
Release GIL around blocking Win32 API calls in native functions

### LINKED ISSUE #2731: CredUIPromptForCredentials blocks background threads
`win32cred.CredUIPromptForCredentials` blocks background threads from running while the main thread displays the prompt dialog.  This does not happen with `MessageBox` or when calling the corresponding functions via ctypes. Maybe `win32cred` is not releasing the GIL when it should?

The [attached script](https://github.com/user-attachments/files/26609811/credtest.py) demonstrates this by printing a sequence of numbers in a background thread while displaying a dialog in the main thread. When calling `win32gui.MessageBox` (test case 1) or calling `CredUIPromptForCredentialsW` via ctypes (test case 3), the background thread continues printing numbers; when calling `win32cred.CredUIPromptForCredentials` (test case 2), the background thread might print one or two numbers but then stops.

## Expected behavior
Background threads should continue executing while the main thread displays the dialog box.

## Actual behavior
Background threads do not execute while the main thread displays the dialog box.

## Steps to reproduce the problem
1. Run the attached script `credtest.py`.
2. Choose test case 2 from the menu.
3. Observe that the background thread stops printing numbers.

## System information

Python version and distribution: 3.11.9 (64-bit)

pywin32 version: build 311

Windows Version: 10.0.26100.1

DLL locations:
```
...\venv\Lib\site-packages\pywin32_system32\pywintypes311.dll
...\venv\Lib\site-packages\pywin32_system32\pythoncom311.dll
```

The problem is also reproducible with build 227 on 32-bit Python 3.6.

### PR DESCRIPTION
**Pull request by staer**
We noticed in our project that several Win32 API calls were blocking the main thread for 100ms–2s+ each, preventing our asyncio event loop from making progress. After investigation, we found that a number of hand-written native functions call Win32 APIs without releasing the GIL. None of these functions access Python objects during the syscall, so holding the GIL is probably unnecessary.

### CODE REVIEW

File: win32/src/win32net/win32netuser.cpp [hunk 1]
```diff
@@ -373,8 +373,10 @@ PyObject *PyNetUserEnum(PyObject *self, PyObject *args)
     if (!FindNET_STRUCT(level, user_infos, &pInfo))
         goto done;
 
-    err = NetUserEnum(szServer, level, filter, &buf, dwPrefLen, &numRead, &totalEntries, &resumeHandle);
-    if (err != 0 && err != ERROR_MORE_DATA) {
+    Py_BEGIN_ALLOW_THREADS err =
```
Comment (mhammond) [inline win32/src/win32net/win32netuser.cpp]: Thanks! I see how you copied the existing style, but sadly that "style" came from an erroneous auto-format some years ago, and I'm trying to fix them as we touch them.  Could you please change these to taking a semi-colon and newlines after the macros? eg, [like this code](https://github.com/mhammond/pywin32/blob/d87033125d238dea6cb3972733bedf028550b204/com/win32comext/authorization/src/authorization.cpp#L26)

**Review by mhammond — COMMENTED** [review]
Sorry to request the formatting changes. Updating this to also handle https://github.com/mhammond/pywin32/pull/2732 would be fantastic.

File: win32/src/win32net/win32netuser.cpp (hunk 1 above)
Comment (staer) [reply win32/src/win32net/win32netuser.cpp]: will do!

Comment (Avasam) [reply win32/src/win32net/win32netuser.cpp]: There's an option to handle this in clang-format
- https://github.com/mhammond/pywin32/pull/2733

But adding a trailing `;` also works since an empty statement after a brace still results in correct code.

Pros&cons can be discussed on that PR. For here it's sufficient to add `;`

**Comment by Avasam** [comment]
> Sorry to request the formatting changes. Updating this to also handle #2732 would be fantastic.

Did you mean https://github.com/mhammond/pywin32/issues/2731 ?

**Comment by staer** [comment]
Fixed formatting, added #2731 to the list of calls changed and updated error handling a little bit. The 3.13, arm64 failure I think is just a test flake not related to this change.

**Comment by Avasam** [comment]
> The 3.13, arm64 failure I think is just a test flake not related to this change.

Yeah that's https://github.com/mhammond/pywin32/issues/2203

**Review by mhammond — APPROVED** [review]
thanks!
